[fog_bolt]
target = "enemy"
persistent = true
mana_cost = 4
elements = [ "wind", "water" ]
effect = "deal_damage_and_afflict_if_unblocked", params = {
    damage_amount = 2,
    affliction = "water",
}

[sell]
target = "enemy"
extra_targets = [{ type = "hand_card", from = "self" }]
effect = Sell

[heal_or_damage]
target = "self"
effect = "heal_or_damage", params = {
    heal_chance = 0.5,
    heal_amount = 10,
    damage_amount = 10,
}

[sun_amulet]
playable = false
persistent = true
hooks = [
    on_death = [
        "set_hp", params = { amount = 10 }
    ]
]